[package]
name = "stashlog"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
tempfile = "3.2"

[dependencies]
chrono = "0.4.38"
gethostname = "0.5.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.121"
